config/routes.rb
Rails.application.routes.draw do

  root :to => 'page#index'
  get 'home' => 'page#index'
  get 'about' => 'page#about'
  get 'clothes' => 'page#clothes'
  get 'gallery' => 'page#gallery'
  get 'contact' => 'page#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale 
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/set_language_controller.rb
class SetLanguageController < ApplicationController
  def hu
    I18n.locale = :hu
    set_session_and_redirect
  end

  def en
    I18n.locale = :en
    set_session_and_redirect
  end

  def de
    I18n.locale = :de
    set_session_and_redirect
  end

  def fr
    I18n.locale = :fr
    set_session_and_redirect
  end

  def ru
    I18n.locale = :ru
    set_session_and_redirect
  end

  def al
    I18n.locale = :al
    set_session_and_redirect
  end

  def il
    I18n.locale = :il
    set_session_and_redirect
  end

  private
  def set_session_and_redirect
    session[:locale] = I18n.locale
    redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/set_language_helper.rb
module SetLanguageHelper
end

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
    <div class="row">

		<div class="col-xs-12 col-sm-4 col-md-4">
			
		</div>

		<div class="col-xs-12 col-sm-4 col-md-4">
			<img class="img-responsive" id="footer-logo" src="/img/BugackuTileReflected.png" />			
		</div>

		<div class="col-xs-12 col-sm-4 col-md-4">
			<p class="hidden-xs">BUGACKU | <%= Date.current.year %></p>
		</div>

    </div>

</footer>

app/views/layouts/_localization.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      
      <div class="modal-header text-uppercase">
        <button type="button" class="close" data-dismiss="modal">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </button>
        <h4 class="modal-title">Languages</h4>
      </div>
      
      <div class="modal-body">
      <div class="row">
      <div class="col-xs-12 col-sm-4">
      <p>EUROPE</p>
      <ul>
      <li>
<%= link_to('HUNGARY', {locale: :hu}, {:class => 'flag-hu'}) %></li>
<li>
<%= link_to('UNITED KINGDOM', {locale: :en}, {:class => 'flag-en'}) %></li>
<li>
<%= link_to('DEUTSCHLAND', {locale: :de}, {:class => 'flag-de'}) %></li>
<li>
<%= link_to('FRANCE', {locale: :fr}, {:class => 'flag-en'}) %></li>
 </ul>
          </div>
          <div class="col-xs-12 col-sm-4">
          <p>OTHERS</p>
      <ul>
<li>
<%= link_to('РОССИЯ', {locale: :ru}, {:class => 'flag-en'}) %></li>
<li>
<%= link_to('ALBANIA', {locale: :al}, {:class => 'flag-en'}) %></li>
<li>
<%= link_to('ISRAEL', {locale: :il}, {:class => 'flag-en'}) %></li>
</ul>
      </div>
          </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="full-navbar">
<div class="container-fluid" id="custom-navbar">
<div class="navbar-header">
<button type="button" class="navbar-toggle rotate" data-toggle="collapse" data-target="#myNavbar">
	    <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span> 
      </button>
       <a class="navbar-brand"></a>
       </div>
	<div class="collapse navbar-collapse navbar-right" id="myNavbar">
	<ul class="nav navbar-nav">
		<li  id="navbar-box"><%= link_to t(:Homepage), root_path %></li>
		<li  id="navbar-box"><%= link_to t(:About), about_path %></li>
		<li  id="navbar-box"><%= link_to t(:Clothes), clothes_path %></li>
		<li  id="navbar-box"><%= link_to t(:Gallery), gallery_path %></li>
		<li  id="navbar-box"><%= link_to t(:Contact), contact_path %></li>
		<li  data-toggle="modal" data-target="#myModal"><a class="text-uppercase">
		<span class="glyphicon glyphicon-globe"></span> (<%= I18n.locale %>)
		</a><li>
	</div>
</div>
</nav>
<%= render "layouts/localization" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bugacku Fashion</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="theme-color" content="#2E2E2C">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= render "layouts/navbar" %>

<content>
<div id="tartalom-wrapper">

<div class="" id="tartalom">

<%= yield %>

</div>

</div>
</content>

<%= render "layouts/footer" %>

</body>
</html>

app/views/page/about.html.erb
<h1 id="page-name"><%= t('About') %></h1>
<div class="container">
  <ul class="nav nav-tabs" id="about-pill">
    <li class="active" ><a href="##menu1"><%= t('vision') %></a></li>
    <li><a href="##menu2"><%= t('mission') %></a></li>
    <li><a href="##menu3"><%= t('faith') %></a></li>
  </ul>
  <div class="tab-content" id="about-pres">
    <div id="menu1" class="tab-pane fade in active">
      <h1><%= t('vision') %></h1>
      <p><%= t('vision-content') %></p>
    </div>
    <div id="menu2" class="tab-pane fade">
      <h1><%= t('mission') %></h1>
      <p><%= t('mission-content') %></p>
    </div>
    <div id="menu3" class="tab-pane fade">
      <h1><%= t('faith') %></h1>
      <p><%= t('faith-content') %></p>
    </div>
  </div>
</div>

app/views/page/clothes.html.erb
<h1 id="page-name"><%= t('Clothes') %></h1>

app/views/page/contact.html.erb
<h1 id="page-name"><%= t('Contact') %></h1>

app/views/page/gallery.html.erb
<h1 id="page-name"><%= t('Gallery') %></h1>
<div>
<ul class="row" id="lightGallery">

</ul>
</div>

app/views/page/index.html.erb
<div id="myCarousel" class="carousel slide hidden-xs" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img class="img-responsive" src="/img/bgss.jpg" alt="Chania" width="1200" height="650">
        <div class="carousel-caption">
          <h3>Chania</h3>
          <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
        </div>
      </div>

      <div class="item">
        <img class="img-responsive" src="/img/bgss.jpg" alt="Chania" width="1200" height="650">
        <div class="carousel-caption">
          <h3>Chania</h3>
          <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
        </div>
      </div>
    
      <div class="item">
        <img class="img-responsive" src="/img/bgss.jpg" alt="Flower" width="1200" height="650">
        <div class="carousel-caption">
          <h3>Flowers</h3>
          <p>Beatiful flowers in Kolymbari, Crete.</p>
        </div>
      </div>

      <div class="item">
        <img class="img-responsive" src="/img/bgss.jpg" alt="Flower" width="1200" height="650">
        <div class="carousel-caption">
          <h3>Flowers</h3>
          <p>Beatiful flowers in Kolymbari, Crete.</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<div class="container" id="welcome">
<h1><%= t('welcome') %></h1>
<p><%= t('about1') %></p>
</div>

app/views/set_language/al.html.erb
<h1>SetLanguage#al</h1>
<p>Find me in app/views/set_language/al.html.erb</p>

app/views/set_language/de.html.erb
<h1>SetLanguage#de</h1>
<p>Find me in app/views/set_language/de.html.erb</p>

app/views/set_language/en.html.erb
<h1>SetLanguage#en</h1>
<p>Find me in app/views/set_language/en.html.erb</p>

app/views/set_language/fr.html.erb
<h1>SetLanguage#fr</h1>
<p>Find me in app/views/set_language/fr.html.erb</p>

app/views/set_language/hu.html.erb
<h1>SetLanguage#hu</h1>
<p>Find me in app/views/set_language/hu.html.erb</p>

app/views/set_language/il.html.erb
<h1>SetLanguage#il</h1>
<p>Find me in app/views/set_language/il.html.erb</p>

app/views/set_language/ru.html.erb
<h1>SetLanguage#ru</h1>
<p>Find me in app/views/set_language/ru.html.erb</p>